[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
norecursedirs = .git .tox venv migrations
addopts =
    --strict-markers
    --tb=short
    --cov=habits
    --cov=users
    --cov=telegram_bot
    --cov-report=term-missing
    --cov-report=html